# Generated by Django 3.2 on 2023-01-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blaind', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaliyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Basic', models.BigIntegerField(default=0)),
                ('Standard', models.BigIntegerField(default=0)),
                ('Premium', models.BigIntegerField(default=0)),
            ],
        ),
    ]
