# Generated by Django 3.2 on 2023-01-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blaind', '0002_daliyprice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='daliyprice',
            table='DaliyPrice',
        ),
    ]
